### ISSUE TITLE
Setup Server Storage

### ISSUE THREAD

**Issue by Arkonos** [Arkonos/server#2]
## ToDo
- [x] Install drives and HBA
- [x] Label drives and cable
- [x] Setup raidz2 including a hot spare
- [x] setup a vm using all or most of that zpool
- [ ] lookup and test resizing [won't do]
- [x] make sure we have planned scrubs
- [x] Test the hot spare?
- [x] Documentation
